package com.example.contacts.database;

public enum DataBaseComands {
    USER_ENTER,
    USER_REGISTRY,
    USER_CHECK_REGISTRY,
    CONTACT_ADD,
    CONTACT_DELETE,
    CONTACT_GET_ALL,
    CONTACT_SORT_NAME_UP,
    CONTACT_SORT_NAME_DOWN,
    CONTACT_SORT_DATE_UP,
    CONTACT_SORT_DATE_DOWN
}
